"use server";

// Define the shape of our data
export type Message = {
    id: string;
    name: string;
    email: string;
    message: string;
    date: string;
};

export type Content = {
    resumeLink: string;
    bio: string;
    github: string;
    linkedin: string;
    heroRoles?: string;
    seoTitle?: string;
    seoDescription?: string;
    fiverr?: string;
    email?: string;
};

// --- Supabase Helper ---
async function supabaseFetch(path: string, options: RequestInit = {}) {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!supabaseUrl || !supabaseKey) {
        throw new Error("Supabase configuration missing (SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY)");
    }

    const url = `${supabaseUrl}${path}`;
    return fetch(url, {
        ...options,
        headers: {
            "apikey": supabaseKey,
            "Authorization": `Bearer ${supabaseKey}`,
            "Content-Type": "application/json",
            "Prefer": "return=representation",
            ...options.headers,
        },
    });
}

// --- Server Actions ---

// Send a new message from the contact form
export async function sendMessage(formData: FormData) {
    const name = formData.get("name") as string;
    const email = formData.get("email") as string;
    const message = formData.get("message") as string;

    if (!name || !email || !message) {
        return { error: "All fields are required" };
    }

    try {
        // 1. Save to Supabase
        const dbResponse = await supabaseFetch("/rest/v1/messages", {
            method: "POST",
            body: JSON.stringify({
                name,
                email,
                message,
                // date is auto-generated by Supabase
            }),
        });

        if (!dbResponse.ok) {
            console.error("Supabase Save Error:", await dbResponse.text());
            return { error: "Failed to save message to database" };
        }

        // 2. Get configuration for email notification
        const contentRes = await getContent();
        const targetEmail = contentRes.email || "ayushchaudhary7652@gmail.com";

        // 3. Email Notification logic (Resend)
        const RESEND_API_KEY = process.env.RESEND_API_KEY;
        if (RESEND_API_KEY) {
            try {
                const mailResponse = await fetch("https://api.resend.com/emails", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "Authorization": `Bearer ${RESEND_API_KEY}`,
                    },
                    body: JSON.stringify({
                        from: "Portfolio <onboarding@resend.dev>",
                        to: targetEmail,
                        subject: `New Message from ${name} via Portfolio`,
                        html: `
                            <div style="font-family: sans-serif; padding: 20px; color: #333;">
                                <h2 style="color: #bc13fe;">New Contact Form Submission</h2>
                                <p><strong>Name:</strong> ${name}</p>
                                <p><strong>Email:</strong> ${email}</p>
                                <p><strong>Message:</strong></p>
                                <div style="background: #f5f5f5; padding: 15px; border-radius: 8px;">
                                    ${message.replace(/\n/g, '<br>')}
                                </div>
                            </div>
                        `,
                    }),
                });

                if (!mailResponse.ok) {
                    const errorData = await mailResponse.json();
                    console.error("Resend API Error:", errorData);
                    return { success: true, emailError: errorData.message || "Email service notification failed" };
                }
            } catch (err) {
                console.error("Resend Network Error:", err);
            }
        }

        return { success: true };
    } catch (err: any) {
        console.error("SendMessage Error:", err);
        return { error: err.message || "An unexpected error occurred" };
    }
}

// Fetch all messages for the admin panel
export async function getMessages(): Promise<Message[]> {
    try {
        const response = await supabaseFetch("/rest/v1/messages?select=*&order=date.desc");
        if (!response.ok) return [];
        return await response.json();
    } catch (err) {
        console.error("GetMessages Error:", err);
        return [];
    }
}

// Delete a message by ID
export async function deleteMessage(id: string) {
    try {
        const response = await supabaseFetch(`/rest/v1/messages?id=eq.${id}`, {
            method: "DELETE"
        });
        return { success: response.ok };
    } catch (err) {
        console.error("DeleteMessage Error:", err);
        return { success: false };
    }
}

// Fetch dynamic content
export async function getContent(): Promise<Content> {
    const fallback: Content = {
        resumeLink: "/resume.pdf",
        bio: "Turning data into intelligence and securing the digital world.",
        github: "https://github.com/Ayushs777",
        linkedin: "https://www.linkedin.com/in/ayush777",
        heroRoles: "Data Analyst, Cybersecurity Enthusiast, AI/ML Learner",
        seoTitle: "Ayush Chaudhary | Portfolio",
        seoDescription: "Turning data into intelligence and securing the digital world.",
        fiverr: "https://www.fiverr.com/ayushchaudh/buying?source=avatar_menu_profile",
        email: "ayushchaudhary7652@gmail.com"
    };

    try {
        const response = await supabaseFetch("/rest/v1/content?select=*&limit=1");
        if (!response.ok) return fallback;
        const data = await response.json();

        if (data && data.length > 0) {
            // Map Supabase snake_case to CamelCase if necessary, but I used snake_case in SQL for safety.
            // Let's assume the component expects what we defined in Content type.
            const item = data[0];
            return {
                resumeLink: item.resume_link,
                bio: item.bio,
                github: item.github,
                linkedin: item.linkedin,
                heroRoles: item.hero_roles,
                seoTitle: item.seo_title,
                seoDescription: item.seo_description,
                fiverr: item.fiverr,
                email: item.email
            };
        }
        return fallback;
    } catch (err) {
        console.error("GetContent Error:", err);
        return fallback;
    }
}

// Update dynamic content from admin panel
export async function updateContent(formData: FormData) {
    const updateData = {
        resume_link: formData.get("resumeLink") as string,
        bio: formData.get("bio") as string,
        github: formData.get("github") as string,
        linkedin: formData.get("linkedin") as string,
        fiverr: formData.get("fiverr") as string || "",
        hero_roles: formData.get("heroRoles") as string || "Data Analyst",
        seo_title: formData.get("seoTitle") as string || "Portfolio",
        seo_description: formData.get("seoDescription") as string || "My Portfolio",
        email: formData.get("email") as string || "ayushchaudhary@gmail.com",
    };

    try {
        const response = await supabaseFetch("/rest/v1/content?id=eq.1", {
            method: "PATCH",
            body: JSON.stringify(updateData),
        });

        if (!response.ok) {
            console.error("Supabase Update Error:", await response.text());
            return { error: "Failed to update content in database" };
        }

        return { success: true };
    } catch (err: any) {
        console.error("UpdateContent Error:", err);
        return { error: err.message || "An unexpected error occurred" };
    }
}
